# Generated by Django 5.0.14 on 2025-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_piechart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piechart',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
