# Generated by Django 5.0.14 on 2025-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_piechart_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='piechart',
            name='monthly_income',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
