# Generated by Django 5.0.14 on 2025-09-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_piechart_monthly_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piechart',
            name='monthly_income',
        ),
    ]
